language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"

sudo: required

dist: trusty

install:
    - sudo apt-get update -q
    - sudo apt-get install libfuzzy2 libfuzzy-dev ssdeep
    - wget https://github.com/plusvic/yara/archive/v3.4.0.tar.gz
    - tar zxvf v3.4.0.tar.gz
    - pushd yara-3.4.0
    - ./bootstrap.sh
    - ./configure
    - make
    - sudo make install
    - sudo ldconfig
    - pushd yara-python
    - python setup.py build
    - python setup.py install
    - popd
    - popd
    - pip install -U pip setuptools python-magic yapsy simplejson pydeep
    - if [ $(python -c 'import sys; print(sys.version_info.major)') == '2' ]; then pip install pefile distorm3 ; fi
    - python setup.py build
    - python setup.py install

script:
    - python setup.py test
    - mas.py -h
