language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"

sudo: required

dist: trusty

install:
    - pip install -U pip setuptools python-magic yapsy simplejson pefile
    - sudo make install

script:
    - make test
